In [4]:
num = int(input("Enter a number : "))

factorial = 1
if num == 0 and num == 1:
  factorial =1
else:

  i=1
  while(i<=num):
    factorial = factorial * i
    i=i+1

print("Factorial of number is ",factorial)

Enter a number : 1
Factorial of number is  1


In [13]:
def fact(num):
  factorial =1
  if num==0 & num==1:
    return factorial
  else :
    for i in range(1,num+1):
      factorial = factorial * i

    return factorial

print(fact(4))

24


In [14]:
n = []
n.append(1)
print(n)

[1]


In [15]:
n.append(2)
print(n)

[1, 2]


In [16]:
name = input("Enter your name: ") 
  
# user entered the name 'harssh'
print("hello", name)

Enter your name: Vaibhav
hello Vaibhav


In [17]:
num1 = int(input("Enter num1: "))
num2 = int(input("Enter num2: "))
  
num3 = num1 * num2
print("Product is: ", num3)

Enter num1: 5
Enter num2: 6
Product is:  30


In [18]:
num1 = 34
if(num1>12):
    print("Num1 is good")
elif(num1>35):
    print("Num2 is not goooood...")
else:
    print("Num2 is great")

Num1 is good


In [19]:
import numpy as np

In [21]:
from time import process_time

In [26]:
l = [i for i in range(10000)]
strt = process_time()

l = [i+5 for i in range(10000)]
end = process_time()

print("time = ",end-strt)

time =  0.0011476620000010485


In [25]:
ar = np.array([i for i in range(10)])

strt = process_time()

ar+=5

end = process_time()

print("time = ",end-strt)



time =  0.0008806459999988192


In [27]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [28]:
a.shape

(4,)

In [31]:
b = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)
b.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

In [32]:
x = np.zeros((3,4))

In [33]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
y = np.ones((4,4))

In [35]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
type(y)

numpy.ndarray

In [42]:
z = np.full((5,5),4)

In [43]:
print(z)
z

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [44]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
n = np.random.random((3,3))
n

array([[0.69429292, 0.69659456, 0.01166894],
       [0.39928629, 0.2064929 , 0.55503938],
       [0.79702147, 0.77018759, 0.65874158]])

In [46]:
c = np.random.randint(10,100,(3,3))
c

array([[31, 26, 97],
       [29, 17, 40],
       [92, 42, 46]])

In [47]:
c = np.random.randint(10,100,(3,3))
c

array([[77, 66, 39],
       [60, 35, 94],
       [87, 49, 45]])

In [48]:
print(c)

[[77 66 39]
 [60 35 94]
 [87 49 45]]


In [53]:
v = np.linspace(10,30,5)
print(v)

[10. 15. 20. 25. 30.]


In [55]:
l2 = [10,203,303.36]
np1 = np.asarray(l2)
print(np1)
print(type(np1))
print(type(l2))

[ 10.   203.   303.36]
<class 'numpy.ndarray'>
<class 'list'>


In [56]:
h = np.random.randint(10,99,(4,4))
print(h)

[[30 47 10 76]
 [12 43 30 67]
 [56 14 67 91]
 [58 73 62 97]]


In [57]:
print(h.shape)

(4, 4)


In [58]:
print(h.ndim)

2


In [60]:
print(h.size)
print(h.dtype)

16
int64


In [61]:
np1 = np.random.randint(0,10,(3,3))
np2 = np.random.randint(10,20,(3,3))
print(np1)
print(np2)

[[3 5 6]
 [5 8 3]
 [8 7 7]]
[[15 13 14]
 [19 14 16]
 [18 13 11]]


In [66]:
print(np.add(np1,np2))
print(np1+np2)

[[18 18 20]
 [24 22 19]
 [26 20 18]]
[[18 18 20]
 [24 22 19]
 [26 20 18]]


In [67]:
print(np.subtract(np1,np2))
print(np1-np2)

[[-12  -8  -8]
 [-14  -6 -13]
 [-10  -6  -4]]
[[-12  -8  -8]
 [-14  -6 -13]
 [-10  -6  -4]]


In [68]:
print(np.multiply(np1,np2))
print(np.divide(np1,np2))
print(np1*np2)
print(np1/np2)


[[ 45  65  84]
 [ 95 112  48]
 [144  91  77]]
[[0.2        0.38461538 0.42857143]
 [0.26315789 0.57142857 0.1875    ]
 [0.44444444 0.53846154 0.63636364]]
[[ 45  65  84]
 [ 95 112  48]
 [144  91  77]]
[[0.2        0.38461538 0.42857143]
 [0.26315789 0.57142857 0.1875    ]
 [0.44444444 0.53846154 0.63636364]]


In [2]:
import numpy as np
a = np.random.randint(10,100,(3,4))
print(a)

[[85 59 43 54]
 [69 69 85 20]
 [90 63 77 53]]


In [3]:
b = a.T
b

array([[85, 69, 90],
       [59, 69, 63],
       [43, 85, 77],
       [54, 20, 53]])

In [4]:
b.shape

(4, 3)

In [5]:
b.reshape(4,3)

array([[85, 69, 90],
       [59, 69, 63],
       [43, 85, 77],
       [54, 20, 53]])

In [6]:
b.shape

(4, 3)

In [8]:
b.reshape(3,4)


array([[85, 69, 90, 59],
       [69, 63, 43, 85],
       [77, 54, 20, 53]])

In [9]:
b.shape

(4, 3)

In [10]:
b

array([[85, 69, 90],
       [59, 69, 63],
       [43, 85, 77],
       [54, 20, 53]])

In [11]:
b.T

array([[85, 59, 43, 54],
       [69, 69, 85, 20],
       [90, 63, 77, 53]])